"""
Django settings for CUT_Guide project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ------------------------------------------------------------
# SECURITY SETTINGS
# ------------------------------------------------------------

SECRET_KEY = 'django-insecure-+b3&zs2m=9jt_775(-c&&^f5)uv^4ow+=#!q7g#o+eavadw495'
DEBUG = True
ALLOWED_HOSTS = ["*"]  # Allow all hosts (for development)


# ------------------------------------------------------------
# APPLICATION DEFINITION
# ------------------------------------------------------------

INSTALLED_APPS = [
    # Default Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # GIS support (temporarily disabled - install GDAL first)
    # 'django.contrib.gis',

    # Your custom app(s)
    'Navigator',  # Make sure this matches your app folder name
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CUT_Guide.urls'


# ------------------------------------------------------------
# TEMPLATES
# ------------------------------------------------------------

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Add a global templates directory for project-wide templates
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CUT_Guide.wsgi.application'


# ------------------------------------------------------------
# DATABASE - Using SQLite (temporarily disabled GIS - use standard DB)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# For production, use PostgreSQL + PostGIS:
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.contrib.gis.db.backends.postgis',
#         'NAME': 'cut_guide_db',
#         'USER': 'postgres',
#         'PASSWORD': 'password',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }

# ------------------
# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# For development: additional static files location
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Where collectstatic will collect files for production
STATIC_ROOT = BASE_DIR / "staticfiles"

# Messages Configuration
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

