# Generated by Django 6.0.2 on 2026-01-19 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('total_floors', models.IntegerField(default=1)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('accessibility_features', models.TextField(blank=True, help_text='Wheelchair access, elevators, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField()),
                ('floor_name', models.CharField(blank=True, help_text="e.g., 'Ground Floor', 'Level 1'", max_length=100)),
                ('floorplan_image', models.ImageField(blank=True, null=True, upload_to='floorplans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='Navigator.building')),
            ],
            options={
                'ordering': ['building', 'floor_number'],
                'unique_together': {('building', 'floor_number')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('office', 'Office'), ('classroom', 'Classroom'), ('lab', 'Laboratory'), ('lecture_hall', 'Lecture Hall'), ('meeting_room', 'Meeting Room'), ('storage', 'Storage'), ('other', 'Other')], default='other', max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('office_number', models.CharField(blank=True, help_text='e.g., extension', max_length=50, null=True)),
                ('accessibility_features', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='Navigator.building')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='Navigator.floor')),
            ],
            options={
                'ordering': ['building', 'floor', 'room_number'],
                'unique_together': {('building', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='ServicePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('library', 'Library'), ('admin_office', 'Administration Office'), ('water_point', 'Water Point'), ('toilet', 'Toilet/Restroom'), ('canteen', 'Canteen/Cafeteria'), ('lab', 'Laboratory'), ('classroom', 'Classroom'), ('office', 'Office'), ('parking', 'Parking'), ('medical', 'Medical/Health Center'), ('security', 'Security Post'), ('lost_and_found', 'Lost & Found'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('office_hours', models.TextField(blank=True, help_text="e.g., '9AM-5PM Mon-Fri'", null=True)),
                ('accessibility_features', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='Navigator.building')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='Navigator.floor')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='Navigator.room')),
            ],
            options={
                'ordering': ['service_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buffer_radius_meters', models.IntegerField(default=100, help_text='Proximity radius in meters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_area', to='Navigator.servicepoint')),
            ],
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('pathway_type', models.CharField(choices=[('outdoor', 'Outdoor Path'), ('indoor_corridor', 'Indoor Corridor'), ('staircase', 'Staircase'), ('ramp', 'Ramp/Slope'), ('elevator', 'Elevator'), ('escalator', 'Escalator')], max_length=30)),
                ('distance_meters', models.FloatField()),
                ('estimated_time_minutes', models.FloatField()),
                ('is_accessible', models.BooleanField(default=True, help_text='Wheelchair accessible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('floor_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paths_from_floor', to='Navigator.floor')),
                ('floor_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paths_to_floor', to='Navigator.floor')),
                ('end_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paths_to', to='Navigator.servicepoint')),
                ('start_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paths_from', to='Navigator.servicepoint')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_meters', models.FloatField()),
                ('estimated_time_minutes', models.FloatField()),
                ('is_accessible', models.BooleanField(default=True, help_text='Wheelchair accessible route')),
                ('route_type', models.CharField(choices=[('indoor', 'Entirely Indoor'), ('outdoor', 'Entirely Outdoor'), ('mixed', 'Mixed Indoor/Outdoor')], default='mixed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_ends', to='Navigator.servicepoint')),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_starts', to='Navigator.servicepoint')),
            ],
            options={
                'unique_together': {('start_point', 'end_point')},
            },
        ),
    ]
